### ISSUE TITLE
3.2.1 Release request

### ISSUE THREAD

**Issue by elrodro83** [cglib/cglib#61]
Hi,

It would be great to have the release that contains the permgen leak fix, so that spring can repackage it.

Thanks in advance.

**Comment by raphw** [comment]
The release must be made by someone with the credentials. The current state would be a clear improvement. @samberl, could you trigger a release?

**Comment by sameb** [comment]
Sure I'll take a look.

**Comment by jhoeller** [comment]
Guys, thanks for your efforts. FYI, we'll be releasing Spring Framework 4.2.5 next Monday (Feb 22). If CGLIB 3.2.1 is available in Maven Central by that time, we'll be happy to include it right away.

**Comment by sameb** [comment]
I just looked over the recent commits and have some concerns about API compatibility, so don't think it's best to push a release right now.

@raphw & @vlsi -- can you chime on on the API compatibility concerns I mentioned @ https://github.com/cglib/cglib/commit/196da25819cd2080f87306c391611f1113e3391a#diff-eec25ed9d2099dbe5d7d1004957aec64L43 ?

**Comment by jhoeller** [comment]
Having had a look at those commits, they do indeed look like significant API changes. Maybe the next release should rather be called CGLIB 3.3 if some of those changes turn out to be necessary?

In any case, no hurries from our side. We'll pick it up for Spring Framework 4.3 then (GA in May).

**Comment by jhoeller** [comment]
Having had a look at those commits, they do indeed look like significant API changes. Maybe the next release should rather be called CGLIB 3.3 if some of those changes turn out to be necessary?

In any case, no hurries from our side. We'll pick it up for Spring Framework 4.3 then (GA in May).

**Comment by vlsi** [comment]
@jhoeller , @sameb ,

Please, point where do you see API changes.
I think I did not modify old tests. This means the API was not changed from test perspective.

I did my best to keep backward compatibility.

**Comment by elrodro83** [comment]
Just created a PR to adress the backward compatibility issue (https://github.com/cglib/cglib/pull/63). Let me know of thatś good for you.

**Comment by sameb** [comment]
I'll try to do a release tomorrow. Thanks for the PR @elrodro83!

**Comment by jhoeller** [comment]
@sameb, @elrodro83, Spring Framework 4.2.5 is a few days behind schedule in the meantime and was meant to go out today now... Given that you intend to release CGLIB 3.2.1 today, we'll be postponing until tomorrow on our end in order to pick it up.

**Comment by sameb** [comment]
3.2.1 is released to maven.  It may take a few hours to appear on maven central.

**Comment by sameb** [comment]
Looks like it's up @ http://central.maven.org/maven2/cglib/cglib/3.2.1/

**Comment by jhoeller** [comment]
@sameb, thanks for your efforts there! I'm in the process of picking it up for Spring Framework 4.2.5. 

Unfortunately we have a regression with respect to proxy class reuse: For the same proxy specifications, we end up with individually generated classes now where previously we got the same class. Any hints appreciated in terms of what could be causing this; I suspect it is directly related to the permgen fix but I got trouble figuring out the actual root of the problem...

**Comment by vlsi** [comment]
@jhoeller , do you have a quick example to reproduce the case?

**Comment by jhoeller** [comment]
@vlsi, at this point, I'm debugging failing tests in the Spring Framework test suite, e.g.: `org.springframework.aop.framework.CglibProxyTests.testMultipleProxies()` in the spring-context module. I'll isolate a minimal example ASAP, not least of it all to find out about the differences. 

One thing I've noticed already is that a `ClassLoader` has to be specified now, whereas previously that wasn't strictly necessary, due to synchronization performed on the Enhancer's `ClassLoader` reference now. This should be easy enough to address on our end but is technically also a subtle regression.

**Comment by sameb** [comment]
Thanks for helping to isolate the minimal repro!  Please do point out any more regressions.  

@vlsi, can we do anything about the class loader issue @jhoeller referred to?

**Comment by jhoeller** [comment]
The reuse issue seems to be something rather involved with the enhancer cache key when backed by a Spring AOP `ProxyCallbackFilter`. A quick plain `Enhancer` based test against the same target class passes for me, reusing the proxy class as expected.

As for the class loader issue, it's a new `synchronized` block in `AbstractClassGenerator.generate` which expects `ClassLoaderData.getClassLoader()` to be non-null... and if no `ClassLoader` has been specified on the `Enhancer`, that one seems to return null. FWIW, I'm also running into that issue just in specific cases... I guess depending on whether there is a cache hit or cache miss, can't tell yet. For Spring's purposes, it is easy enough to sort out though, simply explicitly specifying `proxySuperClass.getClassLoader()` on the `Enhancer` if no `ClassLoader` has been given otherwise (i.e. not implicitly relying on `Enhancer.getDefaultClassLoader()`).

**Comment by vlsi** [comment]
> synchronized block in AbstractClassGenerator.generate which expects ClassLoaderData.getClassLoader() to be non-null.

It might take me a while to setup IDE to run spring-framework tests, however the "classloader issues" might be due to wrong classloader being used in `new ClassLoaderData(classLoader)`: https://github.com/cglib/cglib/blob/ef8fdd49bc71932486d4bd2d489414f8452f579a/cglib/src/main/java/net/sf/cglib/core/AbstractClassGenerator.java#L260-L268

It looks like as if local `ClassLoader loader` should be better there.

**Comment by jhoeller** [comment]
A quick update: It's indeed about `CallbackFilter` equality - a plain `Enhancer` test specifying the simplest possible `CallbackFilter` fails to reuse the proxy class, even if the `CallbackFilter` implements `equals` and `hashCode` accordingly. The test just passes if the `CallbackFilter` is the very same instance...

**Comment by jhoeller** [comment]
And one more: Hacking Spring's `CglibAopProxy` implementation to reuse the `ProxyCallbackFilter` instance makes the problem go away. So it indeed seems that, as of 3.2.1, `Enhancer` requires a `CallbackFilter` to be instance-identical for a proxy class to get reused... whereas previously it accepted `CallbackFilters` that were equal according to their `equals`/`hashCode` implementation.

**Comment by vlsi** [comment]
> a plain Enhancer test specifying the simplest possible CallbackFilter fails to reuse the proxy class, even if the CallbackFilter implements equals and hashCode accordingly

@jhoeller , can you just reuse `CallbackFilter` instances?

I might need to rethink WeakIdentityKey: https://github.com/cglib/cglib/commit/c1d6d31b06a423a173d11a9111bee43999793e37#diff-173a9c4b512f39086ed564b6320318e2R378

Having strong reference to the original `CallbackFilter` will hold a strong reference to its `ClassLoader`, thus introduce a memory leak.

Personally, I do not like how `CallbackFilter` serves two purposes: it acts as a filter and as a cache key. It would be nice if we could isolate "cache key" part from "filtering" part.

**Comment by vlsi** [comment]
On the other hand, I see nothing that prevents using "source object" for hashCode/equals if `WeakReference` is not yet expired.

I do not remember why I used identity-based key.

**Comment by vlsi** [comment]
I just tested equals/hashCode delegation in WeakIdentityKey, and cglib tests still pass, thus it seems to be a missing optimization.

**Comment by jhoeller** [comment]
Technically, we could quite easily manage a canonical `ProxyCallbackFilter` instance for each advised Spring bean. We'd have to extract our own cache key, based on `ProxyCallbackFilter`'s current `equals` implementation, and store the filter instance accordingly. Of course, we'd have to carefully avoid a permgen leak of our own there but I suppose that'd be manageable.

However, this is nevertheless a regression. Spring's repackaged version of CGLIB is used in other places in the Spring portfolio as well, and we can't update all of those places to manage a canonical `CallbackFilter` instance right away. We could only really do that as of Spring Framework 4.3, where we have a release candidate phase to go through in a couple of months.

So the key question is: Will CGLIB 3.2.2 restore equality support for `CallbackFilters`? Sounds like that's feasible? Or will we have to adapt to filter instance identity in the long run?

**Comment by vlsi** [comment]
> Will CGLIB 3.2.2
>Sounds like that's feasible? 

Technically speaking, that depends on @sameb 's bandwidth.
@sameb , what is the probability to release 3.2.2 in the observable future?

**Comment by vlsi** [comment]
> However, this is nevertheless a regression

I would agree.

**Comment by jhoeller** [comment]
For the time being, we can simply stick with CGLIB 3.2.0 in Spring Framework 4.2.5 and possibly in the entire 4.2.x line, living with the permgen behavior that's been around so many years already. It would be good to have a CGLIB 3.2.2 for Spring Framework 4.3 though but that's still a few months to go.

**Comment by sameb** [comment]
I don't have the time to do dev work, but I can release a 3.2.2 when the
code is ready. I agree that this is a regression we don't want. We need to
reinstate support for equals/hashCode equality, IMHO even if the original
filter has been GC'd (because we don't know the usage patterns here).

Re: the cglib tests -- don't rely on them for much. They are far from
exhaustive. When changing code, you'll typically want to write regression
tests for the old behavior to make sure it didn't change.

@vlsi, do you think it's possible to still kill the classloader leak even
if we need to keep the old equals/hashCode semantics?  If not, I think we
just need to ditch that new code and revert to how it was before. If so,
great.

How long do you think it would take to make things stable again?  I'd like
to make sure the most recent release doesn't have regressions. Is there a
way to redact or mark bad a Maven release?

**Comment by vlsi** [comment]
>do you think it's possible to still kill the classloader leak even
if we need to keep the old equals/hashCode semantics? 

I think so.
Classloader leak is covered by the cglib tests (it was added as a part of the feature development). As I said earlier, proper equals/hashCode delegation does not break cglib tests => it should be easily doable.

>  When changing code, you'll typically want to write regression
tests for the old behavior to make sure it didn't change.

The problem with "regression" tests is you never have 100% coverage.
I think I deliberately went with "identity" based keys, then never reconsidered to resort to equals delegation.

It would be good if we could add spring-framework tests to cglib's Travis job. That would probably increase regression coverage.

>How long do you think it would take to make things stable again?

I think I can make that in a day or two.

>Is there a way to redact or mark bad a Maven release?

I think the best way is to resease a subsequent one.
Some comments at "github/release" would help as well.

**Comment by jhoeller** [comment]
The most important assumption that Spring makes, as far as my analysis goes, is indeed `CallbackFilter` equality leading to the reuse of proxy classes. Some tests for that will cover quite a bit of ground already. Beyond that, the Spring Framework test suite has plenty of integration tests, of course...

**Comment by sameb** [comment]
I added a warning to the release notes. Let me know if I summarized it
incorrectly. Thanks for all the help, everyone!

**Comment by vlsi** [comment]
I think #65 and #66 should sort the issues out. However I did not configure spring project yet, so there might be other failures.

**Comment by elrodro83** [comment]
I ran the spring build with this fixes and it ran correctly. I created https://github.com/cglib/cglib/issues/69 for a release including those changes.
